### ISSUE TITLE
The init.rb does not reflect the fact you created your own plugin

### ISSUE THREAD

**Issue by Androc** [Hopebaytech/redmine_mail_reminder#21]
You should update the init.rb to reflect the fact you created a "new" plugin (version, author, url, etc.)

**Comment by Androc** [comment]
The pending problem is the plugin's directory won't match the new plugin's name.

Do you know the right steps to rename a plugin's directory ?

**Comment by jcppkkk** [comment]
The name redmine_issue_reminder was already registered on site (http://www.redmine.org/plugins/redmine_issue_reminder/) so i have to use a different name. Actually i don't know how to rename plugins in redmine system. It would be grateful if you could share any information about how to rename a redmine plugin.

**Comment by Androc** [comment]
I know the name was already registered but the problem is, the original package of Redmine Issue Reminder created a `plugins/redmine_issue_reminder` directory.
Now you have created Mailer Reminder, the directory should be `redmine_mail_reminder`.
You do not need to modify the redmine.org's name, just modify the init.rb to put the right new directory (`redmine_mail_reminder`), the author (you), the version (3.0.0).

**Comment by Androc** [comment]
## Yeah ! I found the solution ! :) ##

To be coherent, I think you should :
1. rename your github repository to `redmine_mail_reminder`
2. modifiy the `init.rb` of the plugin to replace `Redmine::Plugin.register :redmine_issue_reminder do` to `Redmine::Plugin.register :redmine_mail_reminder do` (*IMPORTANT*)
3. still in `init.rb`, modify `author`, `version`, `url`, etc.

## Solution for "migrate" from old to new name ##

If you have already installed `redmine_issue_reminder` and want to "migrate" to `redmine_mail_reminder` (in fact, it is just a renaming, to have the ability to check the update on redmine.org) :
1. rename your `redmine_issue_reminder` directory (`{REDMINE_ROOT}/plugins/redmine_issue_reminder`) to `redmine_mail_reminder`
2. connect to your redmine's SQL database
3. run the following SQL script `update schema_migrations set version=replace(version, 'redmine_issue_reminder', 'redmine_mail_reminder') where version like '%redmine_issue_reminder%';`
4. run the following rake `rake redmine:plugins:migrate`
5. restart your web server (usually `/etc/init.d/apache2 restart`)

And that's it. Now you can check for updates of the plugin and it is all coherent.

**Comment by Androc** [comment]
I missed something, the `settings/plugin/redmine_mail_reminder` is now empty.

**Comment by Androc** [comment]
I definitely missed something as `rake reminder:exec[test]` gives me this : `NoMethodError: undefined method 'plugin_redmine_issue_reminder' for #<Class:0xb882a10>`

**Comment by Androc** [comment]
The file `app/models/issue_reminder_mailer.rb` must be also modified.
Line 60, `plugin_redmine_issue_reminder` to `plugin_redmine_mail_reminder`

**Comment by Androc** [comment]
I fixed all the problems I encountered. Now it seems to work for real.

I know I should make a pull request but :
1. it is a bit tricky to give a fully automated method for migrate
2. I have a problem with my Git skills and I am not able to push on my redmine2.6 branch :)

**Comment by jcppkkk** [comment]
@Androc You can push to your forked repo's 2.6 branch. then go to the page of my 2.6 branch and click the green button? (I'am not sure about this)
![image](https://cloud.githubusercontent.com/assets/84070/6802925/2c97f7c6-d26f-11e4-9b31-2f94188eb2d2.png)

**Comment by Androc** [comment]
I know how to make a pull request, my problem is "push on my repo 2.6 branch", I have an error and can't push.
I had to create a branch 2.6, git did not created it by itself when I first tried to push even, if I developed on it.

**Comment by jcppkkk** [comment]
Could you paste the git command and error message here? I may be able to help you in this case.

**Comment by Androc** [comment]
I am not sure it is possible to automated the solution because you must rename the plugin's folder.

The only good part about my solution is that you are able to check updates because, once you made all the modifications, the plugin's directory matches the name of your plugin on redmine.org.

The only mandatory modification is the init.rb where you must put the right author, version and url.

Anyway, here is what I have :
`git branch`
output :
```
  master
* redmine2.6
```

`git push --repo https://github.com/Androc/redmine_issue_reminder`
output :
```
To https://github.com/Androc/redmine_issue_reminder
 ! [rejected]        redmine2.6 -> redmine2.6 (non-fast-forward)
error: failed to push some refs to 'https://github.com/Androc/redmine_issue_reminder'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

I must confess that I did not really search to solve this problem as the changeset I made on init.rb is really trivial

**Comment by Androc** [comment]
I found my problem. Had to pull from *my* (not yours as usual) repository first.

I am still not sure how the renaming could be accomplished without troubles for already installed plugin.

**Comment by jcppkkk** [comment]
@Androc ok, if you encounter any problem please paste the output of following commands to identify the problem.
```
git status
git branch -ra
git remote -v
```

**Comment by jcppkkk** [comment]
I will rename it from issue_reminder to mail_reminder on master branch. After I upgrade mine redmine to 3.0 :zzz:

**Comment by Androc** [comment]
Don't forget that just renaming the plugin is not enough.

**Comment by jcppkkk** [comment]
Plugin is renamed on branch 2.6/3.0

**Comment by Androc** [comment]
Nice ! Thanks to you :)
