### ISSUE TITLE
Issues with README.markdown

### ISSUE THREAD

**Issue by makhomed** [Hopebaytech/redmine_mail_reminder#25]
```
$ rake redmine:plugins:migrate
```
1) this is bad instruction, it should be:
```
rake redmine:plugins:migrate RAILS_ENV="production"
```
----------------

```
$ sudo crontab -e
0 6 * * * cd {REDMINE_ROOT} && rake reminder:exec RAILS_ENV="production" > /dev/null 2>&1
```
2) start plugin under root is not required - it should be started under same account as redmine itself
3) sending email at 06:00 and any day can be inappropriate, may be it is better to send emails at 08:30 and only on work days 1-6 ? 
something like this:
```
$ crontab -e
30 8 * * 1-6 cd {REDMINE_ROOT} && rake reminder:exec RAILS_ENV="production" > /dev/null 2>&1
```

**Comment by Androc** [comment]
I agree with that point 1 should be "fixed" because not everybody has `RAILS_ENV` in environment variables.

For point 2, just put the username before `cd`.
For example : `0 6 * * * redmine_user cd {REDMINE_ROOT} && rake reminder:exec RAILS_ENV="production" > /dev/null 2>&1`

Point 3 it is more a matter of preferences.
I start working early so 06:00 is fine for me and I set the plugin to send email every third day instead of everyday.
Other people may like to receive just one email per week.

**Comment by makhomed** [comment]
>For point 2, just put the username before cd.
>For example : 0 6 * * * redmine_user cd {REDMINE_ROOT} && rake reminder:exec RAILS_ENV="production" > /dev/null 2>&1

In this case - ```$ sudo crontab -e``` - system-wide crontab will be edited.
and with current version of README.markdown - it will be done with root privileges.
This is wrong, because rake should be started under used privileges, the same as redmine itself. 
The most easy way - is just to edit {redmine_user} crontab and don't touch system-wide crontab.
user crontabls edited via ```$ crontab -e``` will be placed inside /var/spool/cron and don't need root privileges to edit it.

> Point 3 it is more a matter of preferences.
> I start working early so 06:00 is fine for me and I set the plugin to send email every third day instead of everyday.
> Other people may like to receive just one email per week.

Most people start working at 08:30, so by default - it plobably will be better to write in README.markdown start tile acceptable by most users.

"to send email every third day" - as I undserstand it will be Sunday sometimes.
if configure "1-6" in crontab - mail will never send in Sunday.

or may be put two crontab examples, one with 06:00 and every day,
and second - at 08:30 and all days except Sunday: "1-6" ?

**Comment by Androc** [comment]
> In this case - $ sudo crontab -e - system-wide crontab will be edited.

Yes, but will be executed as `redmine_user`.

> Most people start working at 08:30, so by default - it plobably will be better to write in README.markdown start tile acceptable by most users.

Is it really a problem if mail is send 2 hours before people start to work ?

**Comment by makhomed** [comment]
>>In this case - $ sudo crontab -e - system-wide crontab will be edited.
>Yes, but will be executed as redmine_user.

In current version of README.markdown - it will be executed as root user.
Better way to execute as redmine user - is just edit redmine user crontab, nut not root one:
```
$ crontab -e
30 8 * * 1-6 cd {REDMINE_ROOT} && rake reminder:exec RAILS_ENV="production" > /dev/null 2>&1
```
in this case command will be executed as remine user in natural order.

> Is it really a problem if mail is send 2 hours before people start to work ?

Sometimes yes, because some people has audible new mail notification on smartphones.

**Comment by Androc** [comment]
I agree about smartphones.

For crontab it is also a matter of preference, it can be "hard" to follow all crontab on several users.

Some admins may prefer to have one crontab to edit but each cron will be executed as different users as in my example.
I think both are valuable.

The point 1 should be fixed as it is an important part of smooth installation.

**Comment by makhomed** [comment]
> For crontab it is also a matter of preference, it can be "hard" to follow all crontab on several users.
> Some admins may prefer to have one crontab to edit but each cron will be executed as different users as in my example.
> I think both are valuable.

Yes, but current suggested command is broken:
```
$ sudo crontab -e
0 6 * * * cd {REDMINE_ROOT} && rake reminder:exec RAILS_ENV="production" > /dev/null 2>&1
```

system-wide crontab requires user name before command.
so just removing useless ```sudo``` this example can be made correct.

If admins prever maintain all user crontabs in one file - they easy can do that.
