### ISSUE TITLE
Closed issue notification

### ISSUE THREAD

**Issue by atopcu** [Hopebaytech/redmine_mail_reminder#26]
Thanks for this plugin. It will be mode usefull for me with following enhancements:
1)  is it possible to use a customisable name instead of Anonymous as issue updater. 
2) there is needed a more descriptive comment in that mail and it should be in local language. 

I'm not sure these are easy or not. 

Best regards.

**Comment by Androc** [comment]
Hello,

1/ Do you speak about the subject of the mail? It is globally configurable
2/ Do you mean it should be possible to configure a description for each
filter?
