### ISSUE TITLE
Error:The page you were trying to access doesn't exist or has been removed

### ISSUE THREAD

**Issue by jigmelam** [Hopebaytech/redmine_mail_reminder#30]
I've just installed the latest version Redmine Mail Reminder on Redmine version 3.0.3.stable, Ruby version 2.0.0-p645. But there are some error: 
1) when select Configure plugin, it show error 404 (The page you were trying to access doesn't exist or has been removed).
2) After add module Issue Reminder on a project, the new appear with title: translation missing:en.issues_reminder

Please help me. Thanks so much!

**Comment by Androc** [comment]
Hello,

I think the installation went wrong (maybe you forgot something).
1. Did you name your `redmine/plugins/redmine_mail_reminder` exactly `redmine_mail_reminder` ? Where does the link go when you hover the link of "Configure plugin" ?
2. I think this problem will be solved when you the 1. will be solved.

Did you restart your apache after installing the plugin ?

**Comment by jigmelam** [comment]
it work now. Thank you so much!

**Comment by Androc** [comment]
Glad I could help :)

What was the problem ? Wrong directory's name ?

Don't forget to close the issue.

**Comment by jigmelam** [comment]
yes, as you said. The reason is wrong directory's name.
Thank you!

**Comment by Androc** [comment]
No problem. Enjoy your plugin :)
