### ISSUE TITLE
crontab issue

### ISSUE THREAD

**Issue by jigmelam** [Hopebaytech/redmine_mail_reminder#32]
I setup send mail on 8h30 everyday but: 
"rake reminder:exec[test]"  is work but "rake reminder:exec"  (no test param) not work!
So I still setup on crontab file with [test] param

Thank you!

**Comment by Androc** [comment]
Read carefully this section : https://github.com/Hopebaytech/redmine_mail_reminder#testing-redminder-mail
* Did you create "issues search" ?
* Does yours "issues search" have results ?
* Maybe you have already successfully execute the `rake reminder:exec` so the "last execution date" is set and you have to wait one day to try again.

If you `rake reminder:exec[test]` it certainly means that your plugin works (see #3).

**Comment by jigmelam** [comment]
rake reminder:exec  work. Thank you!

**Comment by jcppkkk** [comment]
![image](https://cloud.githubusercontent.com/assets/84070/7959114/ceb99b22-0a28-11e5-94f9-f4169423d0cf.png)
![image](https://cloud.githubusercontent.com/assets/84070/7959130/f794f6cc-0a28-11e5-93c9-16d56ca9c6ea.png)
