### ISSUE TITLE
Translations missing & page not found on project reminders menu.

### ISSUE THREAD

**Issue by janekska** [Hopebaytech/redmine_mail_reminder#41]
Hi, 
In my setup (see bellow) reminder installed fine, but when I started to configure the last step 
"Create reminder with custom query in "Project > Issues Reminder""
does not worked for me:
At the beginning I got missing translation in Issues reminder menu.
I translated it, that it appears fine, but I got "page not found" error.
Then I aboserved that URL format for reminder is a bit different:
http://myredmine.server/mail_reminders?project_id=crm
So I tried this url:
http://myredmine.server/projects/crm/settings
but got the same "page not found"

What could be a problem?
brgds
Janeks

Environment:
  Redmine version                3.0.3.stable
  Ruby version                   1.9.3-p551 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Mercurial                      2.0.2
  Git                            1.7.9.5
  Filesystem                     
Redmine plugins:
  accept                         0.0.1
  event_notifications            3.0.0
  redmine_dashboard              2.5.0
  redmine_mail_reminder          3.0.0.0001
  redmine_theme_changer          0.2.0

**Comment by luisfgfurtado** [comment]
same issue

**Comment by Androc** [comment]
@luisfgfurtado classic mistake ;)
Hope it will work for @janekska too.

**Comment by janekska** [comment]
Ah, my fail - remainder -> reminder :-P
Thanks - it works. At least I can see config page for project now.
I'll test fully latter...

**Comment by Androc** [comment]
Nice :)

**Comment by belka-rzn** [comment]
Hi,
I heve this probles too. But i have Internal error 500 then i started to configure the last step 
"Create reminder with custom query in "Project > Issues Reminder"".  Plugin installed good, all other settings works. Name plugin folder "redmine_mail_reminder". Can you help me?

**Comment by jcppkkk** [comment]
@belka-rzn would you open another issue with redmine log pasted?
