### ISSUE TITLE
Possible to only send reminders when overdue issues exist?

### ISSUE THREAD

**Issue by cguthardt** [Hopebaytech/redmine_mail_reminder#45]
Before I ask my provider to install this plugin, I would like to know if it supports the following:

I would like to receive a nightly email about my overdue issues. If there are no overdue issues, no email should be sent.

Unfortunately, the web site of this plug in does not say if it is possible to receive only overdue issues and if no mails are sent if the query returns an empty result.

Thank you for your help!

**Comment by Androc** [comment]
Hello,

if you are able to perform/save a query that fits your needs, then the plugin reminders will help you.
It just uses the result of the core queries and send to concerned people if there are results.
No mail is sent if there is no result.
