### ISSUE TITLE
Email not send Redmine 3.1.1

### ISSUE THREAD

**Issue by FumbleBe** [Hopebaytech/redmine_mail_reminder#48]
Hi,

With Redmine 3.1.1 and redmine_mail_reminder 3.0.0.0001 when executing:

rake reminder:exec[test] RAILS_ENV="production"
Project "X" with query "Y"         is forced processing under [test] mode.
email@domain.tld

But no email are send...
I got this in configuration.yml:

production:
    delivery_method: :async_sendmail

regards,

**Comment by FumbleBe** [comment]
For information, redmine tell me that the plugin is in version 3.0.0 even if I cloned the master Branch...

So, it also told me that I can update to 3.0.3...

Am I doing smth wrong?

**Comment by Androc** [comment]
Hello,

Go to Administration>Configuration>Notifications, click on Send a test email.

Does it send an email ?

**Comment by FumbleBe** [comment]
Yes !

**Comment by Androc** [comment]
Are you sure your configured filters show issues ?

**Comment by FumbleBe** [comment]
Yes, when I m clicking The filter, it show me the issues of the project.

**Comment by Androc** [comment]
Did you check logs ? No error ? Can you run the command with `--trace` ?

**Comment by FumbleBe** [comment]
I see no errors in the apache logs...
If I do rake reminder:exec[test] RAILS_ENV="production" --trace

** Invoke reminder:exec (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute reminder:exec
Project "TEST" with query "TEST1"        is forced processing under [test] mode.
email@domain.tld

**Comment by Androc** [comment]
It is not in your spams or something like that ? Are you able to listen SMTP traffic from your server ?

I am not the owner of the plugin but I helped him on it so I may miss something.

**Comment by FumbleBe** [comment]
I look at the postfix logs directly on the server, and it s not even trying to send something.

Do you know the version of the plugin Redmine is suppose to display in the plugins window?

**Comment by Androc** [comment]
I am still stuck with the 2.6.0 But looking the sources (https://github.com/Hopebaytech/redmine_mail_reminder/blob/master/init.rb), it appears that the author forgot to increment the version from 3.0.0 to 3.0.3

**Comment by FumbleBe** [comment]
ok... so that's another thing... 

I tried to install from scratch a redmine 3.0 but it is exactly the same. No error, but no mail...

that's pretty annoying...

**Comment by Androc** [comment]
I do some tests monday and will give you feedbacks.

**Comment by FumbleBe** [comment]
Thank you very much!

**Comment by Androc** [comment]
No problem. Hope we will be able to fix your problem.

**Comment by FumbleBe** [comment]
For information, on the same server, I ve tested with redmine 3.0 and the master branch of the plugin, not better.

And with redmine 2.6.7 and 2.6 branch of the plugin, same...

So I came in the conclusion that maybe (probably) the issue is not the plug-in,  But the server... Is there some sort of requirement for the plugin to send email correctly?

The server is an Apache server with fcgi on a Debian 7. And the email server is a postfix installed locally...

**Comment by Androc** [comment]
Hello, sorry, could not make tests yesterday, tons of work.

I am not sure there is hard requirement for the plugin. In my opinion, I thought when you were able to send Test email from Redmine, the plugin shoud work.

**Comment by FumbleBe** [comment]
Is it possible for you to show me what the email looks like when I got a reminder?

**Comment by Androc** [comment]
I tried to find the solution to your problem but not able to find it :(
![2015-10-13_09h06_37](https://cloud.githubusercontent.com/assets/400567/10448005/e1b5edf2-7189-11e5-882a-0802ef3e8924.png)

**Comment by Yaco** [comment]
Hi! I got the very same problem here.

Redmine is able to send emails, below my config: 

```
# = Redmine configuration file
#
# ==== Sendmail command

 production:
   email_delivery:
     delivery_method: :sendmail
```

But this plugin is not sending e-mails at all...

Any clue?

**Comment by Yaco** [comment]
I upgraded to 2.6.9 and using the 2.6 branch of this plugin and still getting this same error...

Any help??

**Comment by FumbleBe** [comment]
I personally do not use this plugin anymore... As I was not able to find a solution....

I am now using my own script requesting the database, and executed by a cron job...

Sorry...

**Comment by Yaco** [comment]
I disabled TLS in my postfix configuration (```smtpd_use_tls=no```) and now it works ok!

**Comment by FumbleBe** [comment]
Well done!

**Comment by andrey-str** [comment]
It also doesn't work for me.

Redmine 3.3.0.stable, turning off TLS doesn't help.
Redmine itself is also able to send out test emails sucessfully.

Here is a my email config:

email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: "my mail server, postfix based"
      port: 25
      authentication: :plain
      user_name: "email address"
      password: ""

**Comment by andrey-str** [comment]
Nevermind, my user wasn't assigned to project I was trying to query.
Works without problem, with TLS with my setup. And THANKS!
