### ISSUE TITLE
Query Reminder is empty

### ISSUE THREAD

**Issue by Etti82** [Hopebaytech/redmine_mail_reminder#52]
Also, if I try to try send test mail - nothing comes. Help me please. Thanks.

rake reminder:exec[test] RAILS_ENV="production" --trace
** Invoke reminder:exec (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute reminder:exec

![2015-11-16 15-23-15 c redmine](https://cloud.githubusercontent.com/assets/15869768/11181784/42fc4c62-8c76-11e5-8261-a26680157dcb.png)

  Redmine version: 3.1.1.stable
  Ruby version: 1.9.3-p0
  Rails version: 4.2.4
  redmine_mail_reminder: 3.0.0.0001

**Comment by Androc** [comment]
Hello,

you need to create a query by going to "Issues" then perform the search you want and click on "Save".
The queries will be available in your plugin

**Comment by Etti82** [comment]
Androc. thanks!

**Comment by Androc** [comment]
No problem :)
