### ISSUE TITLE
[Security] Nokogiri upgrade to 1.6.7.1

### ISSUE THREAD

**Issue by octoquad** [Hopebaytech/redmine_mail_reminder#58]
With Redmine 3.1.3, nokogiri was updated to 1.6.7.1 as a minimum due to security advisories. If you are upgrading from Redmine 3.1.2 to 3.1.3 you will be faced with:

```bash
[!] There was an error parsing `Gemfile`: 
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: nokogiri (>= 1.6.7.1) and nokogiri (>= 1.3). Bundler cannot continue.

 #  from /path/to/redmine/plugins/redmine_mail_reminder/Gemfile:6
 #  -------------------------------------------
 #  gem 'premailer-rails'
 >  gem 'nokogiri', '>=1.3'
 #  
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /home/redmine/redmine/Gemfile:113
 #  -------------------------------------------
 #  Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
 >    eval_gemfile file
 #  end
 #  -------------------------------------------
```

If you set it to >=1.6.7.1 in the Gemfile for the plugin, bundle installs it, but with the following output.

> Your Gemfile lists the gem nokogiri (>= 1.6.7.1) more than once.
> You should probably keep only one of them.

Running a reminder:exec[test] works ok.

Thanks

**Comment by octoquad** [comment]
Link to announcement: https://groups.google.com/forum/#!topic/nokogiri-talk/aSbgDiwb24s

**Comment by maximkrusina** [comment]
Same problem when installing on Redmine 3.3.0

You specified: nokogiri (>= 1.6.7.2) and nokogiri (>= 1.3). Bundler cannot continue.

Any clue how to install?
Thanx!

**Comment by octoquad** [comment]
@maximkrusina My work around to get it working again is to change the Gemfile in /path/to/redmine/plugins/redmine_mail_reminder to match the version of the Redmine Gemfile nokogiri version. 

Replace the line with `gem 'nokogiri' >= 1.3` with `gem 'nokogiri', '>=1.6.7.2'` then do the normal `bundle install` in the Redmine root directory.

This method also works for newer versions for Redmine (I'm currently running 3.2.3).

Hope that helps.
