### ISSUE TITLE
Email reminder for tasks to be start today

### ISSUE THREAD

**Issue by xcellenceit** [Hopebaytech/redmine_mail_reminder#72]
Hi,

Need to check, on whether this supports following? 

1. Email reminder, that following list of tasks are planned to start today

BTW, pointed here from: https://github.com/f0y/due_date_reminder/issues/51#issuecomment-228455300

Regards,
Krunal

**Comment by jcppkkk** [comment]
@xcellenceit As long as you can find a redmine search query to filter out what you want, this plugin can mail it.

**Comment by xcellenceit** [comment]
Hi, Thank you for your response.

Yes we know query, but how to map that to the plugin so that it sends it as an email?

Kindly advise.

**Comment by jcppkkk** [comment]
Hi @xcellenceit 
Is this what you are asking for?

1. Search in redmine and adjust the query until it filter out what you want
2. when you filter things in issues page, there sould be a save botton under filter conditions to let your you save the search into a saved query
3. Enable `Issue reminder` module in module tab under project setting page
4. Create a reminder. in Issue reminder tab, there is a dropdown menu named "Query", which can let you select your saved query at step 2.
![image](https://camo.githubusercontent.com/3843a0007b867cf180e159325c1ffad3f623eaab/687474703a2f2f6661726d372e7374617469632e666c69636b722e636f6d2f363130392f363239343734353030365f343939383665633534315f622e6a7067)
